### ISSUE TITLE
Requesting `supabase==2.2.1`

### ISSUE THREAD

**Issue by ap--** [conda-forge/supabase-feedstock#57]
Hello everyone,

Thanks for maintaining supabase on CF.
Would it be possible to get an old version `2.2.1` added?

Sadly the conda-forge way of adding older versions is a bit convoluted, see here: https://conda.discourse.group/t/how-to-build-old-versions/433/2

I'd be happy to help.

Cheers,
Andreas 😃

**Comment by timkpaine** [comment]
why? that is over a year old so I dont think we will..

**Comment by ap--** [comment]
Thanks for the quick reply!

> why? 

A package I depend on pins `supabase==2.2.1`, and I wanted to move dependencies to conda.

> that is over a year old so I dont think we will..

Makes perfect sense. I'll get this resolved downstream then.

Have a great day!
